# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vigil
email: ane@iki.fi
author: Antoine Kalmbach
description: > # this means to ignore newlines until "baseurl:"
  Turn files into asynchronous streams
baseurl: /vigil # the subpath of your site, e.g. /blog
url: "https://ane.github.io" # the base hostname & protocol for your site
picture: ./assets/vigil.png

# Build settings
markdown: kramdown
theme: minima

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
